language: node_js

node_js:
- 0.10

sudo: false

cache:
  directories:
    - node_modules

env:
  global:
    # GH_TOKEN
    - secure: "d9Lws27Y4WkxV3PlRbACsBj2JIJNw5sNbDe0VZRXlQKFyWt3WO2gAR/+P+/dTnFu8XwD15XC7KL6BLPh2IFAv3YWK2Se/xGSsHSWgP8k+PVTn9t8Rs4Q0IcF3aJ8tzdqN0cY14+9yRN2w7HpJQripCjnZHIgbkgA3/rATtxbhG0="

install:
- npm install
- npm install -g grunt-cli

script:
- grunt broccoli:release:build
- npm test

after_success: .travis/after_success

notifications:
  webhooks:
    urls:
      - "https://webhooks.gitter.im/e/c840be9fc44a2c6bd235"
    on_success: change
    on_failure: always
    on_start: false
