language: node_js

node_js:
- 0.10

sudo: false

cache:
  directories:
    - bower_components
    - node_modules

before_script:
- npm install -g bower broccoli-cli
- bower install --config.interactive=false
- broccoli build release
