language: node_js

node_js:
- 0.10

sudo: false

cache:
  directories:
    - bower_components
    - node_modules

env:
  global:
    secure: "d9Lws27Y4WkxV3PlRbACsBj2JIJNw5sNbDe0VZRXlQKFyWt3WO2gAR/+P+/dTnFu8XwD15XC7KL6BLPh2IFAv3YWK2Se/xGSsHSWgP8k+PVTn9t8Rs4Q0IcF3aJ8tzdqN0cY14+9yRN2w7HpJQripCjnZHIgbkgA3/rATtxbhG0="

install:
- npm install
- npm install -g bower broccoli-cli karma-cli
- bower install --config.interactive=false

script:
- BROCCOLI_ENV=production broccoli build release
- npm test

after_success: .travis/after_success
