language: node_js

node_js:
- 0.10

sudo: false

cache:
  directories:
    - bower_components
    - node_modules

env:
  global:
    # GH_TOKEN
    - secure: "d9Lws27Y4WkxV3PlRbACsBj2JIJNw5sNbDe0VZRXlQKFyWt3WO2gAR/+P+/dTnFu8XwD15XC7KL6BLPh2IFAv3YWK2Se/xGSsHSWgP8k+PVTn9t8Rs4Q0IcF3aJ8tzdqN0cY14+9yRN2w7HpJQripCjnZHIgbkgA3/rATtxbhG0="

install:
- npm install
- npm install -g bower grunt-cli
- bower install --config.interactive=false

script:
- grunt broccoli:release:build
- npm test

after_success: .travis/after_success

notifications:
  webhooks:
    urls:
      # Gitter.im
      - secure: "Axq+vsnQ8Jwb/Vbbjpm9lqDgnm3tmeXdSyScL3QXokhHnUVyQ1O14Uvu7IekQmyPBjJq+/EwORzqhQbrzDlOINcQugOQNbjhxajJO9r2ILqwiIJRnFJ0mxlrVQAP/OZM5t5gPZdJIlMHDSYy6AUVxsygU/bLNsh9a6Ktwz36Z88="
    on_success: change
    on_failure: always
    on_start: false
